In [2]:
print("test")

test


In [3]:
from IPython.display import Image

Image(url='https://imgur.com/5CXo6pt.gif')

In [4]:
import numpy as np

print(np.__version__)

1.26.1


In [5]:
electric_bill = np.array([24.33, 22.99, 50.99, 31.99, 22.99, 23.44])
gas_bill = np.array([34.55, 23.22, 23.44, 44.55, 33.22, 33.12])
wifi_bill = np.array([34.99, 34.99, 34.99, 34.99, 34.99, 34.99])

In [6]:
print(gas_bill)

[34.55 23.22 23.44 44.55 33.22 33.12]


In [7]:
population = np.array([19571216, 19673200, 19854526, 20104710, 19463131, 19544098, 19593849, 19636391, 19657321, 19653431, 19626488])

In [8]:
print(population[0])

19571216


In [9]:
print(population[10]-population[0])

55272


In [10]:
print(population[1:4])

[19673200 19854526 20104710]


In [11]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
print(arr[0])     # Output: [1, 2, 3]
print(arr[1])     # Output: [4, 5, 6]
print(arr[2])     # Output: [7, 8, 9]

[1 2 3]
[4 5 6]
[7 8 9]


In [13]:
print(arr[0][0])  # Output: 1
print(arr[0][2])  # Output: 3
print(arr[2][2])  # Output: 9

1
3
9


In [14]:
seating_plan = np.array([
  [0, 1, 3], 
  [2, 9, 5],
  [6, 7, 10]
])

In [15]:
monthly_budget = np.array([
  [453.88, 192.44, 1750.00, 980.41, 578.22],   # month 1
  [689.77, 256.81, 1750.00, 865.34, 356.84],   # month 2
  [589.23, 293.42, 1850.00, 873.45, 789.23]    # month 3
])

In [16]:
gradebook = np.array([
  [98, 98, 90, 84, 93, 73, 80],                # student 1
  [93, 95, 75, 90, 89, 84, 76],                # student 2
  [90, 89, 88, 84, 90, 67, 72],                # student 3
  [89, 84, 69, 74, 84, 70, 72]                 # student 4
])

In [17]:
egg_carton1 = np.array([
  [0.89, 0.90, 0.83, 0.89, 0.97, 0.98], 
  [0.95, 0.95, 0.89, 0.95, 0.23, 0.99]
])

egg_carton2 = np.array([
  [0.89, 0.95, 0.84, 0.92, 0.94, 0.93], 
  [0.93, 0.95, 0.02, 0.03, 0.23, 0.99]
])

egg_carton3 = np.array([
  [0.83, 0.95, 0.89, 0.54, 0.37, 0.92], 
  [0.98, 0.99, 0.19, 0.23, 0.89, 0.91]
])

In [18]:
avg_egg1 = np.average(egg_carton1)
avg_egg2 = np.average(egg_carton2)
avg_egg3 = np.average(egg_carton3)

print(avg_egg1)
print(avg_egg2)
print(avg_egg3)

0.8683333333333333
0.7183333333333333
0.7241666666666666


In [19]:
 
order = np.array([12.99, 9.99, 4.99, 12.99])

print(order * 0.8)   # Output: [10.39 7.99 3.99 10.39]

[10.392  7.992  3.992 10.392]


In [21]:
tallest_buildings = np.array([2717, 2227, 2073, 1972, 1966, 1819, 1776])
print(tallest_buildings*0.3048)


[828.1416 678.7896 631.8504 601.0656 599.2368 554.4312 541.3248]


In [22]:
temperatures = np.array([[50, 51, 54, 59, 59, 53, 54, 51],
                         [45, 50, 38, 44, 40, 46, 43, 39]])

print(np.min(temperatures))       # Output: 38
print(np.max(temperatures))       # Output: 59
print(np.sum(temperatures))       # Output: 776
print(np.average(temperatures))   # Output: 48.5

38
59
776
48.5


In [24]:

print(np.sum(temperatures, axis=0))   # Sum of each column
print(np.min(temperatures, axis=1))   # Min of each row

[ 95 101  92 103  99  99  97  90]
[50 38]


In [25]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]) 

print(arr.shape)     # Output: (4, 3)

(4, 3)


In [26]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8]) 
new_arr = arr.reshape(2, 4)

print(new_arr)

# Output:
# [[1 2 3 4]
# [5 6 7 8]]

[[1 2 3 4]
 [5 6 7 8]]


In [28]:
month_results = np.array([56, 100, 33, 0, 45, 45, 46, 34, 89, 180, 60, 45, 45, 44, 46, 45, 0, 0, 15, 90, 301, 197, 20, 60, 45, 45, 42, 45])
print(month_results.shape)

new_shape = month_results.reshape(4,7)
print(new_shape)

(28,)
[[ 56 100  33   0  45  45  46]
 [ 34  89 180  60  45  45  44]
 [ 46  45   0   0  15  90 301]
 [197  20  60  45  45  42  45]]


In [33]:
arr = np.arange(start=1, stop=14, step=4)

print(arr)   # Output: [1 4 7]

[ 1  5  9 13]


In [34]:
arr_comet = np.arange(1986,3000,75)
print(arr_comet)

[1986 2061 2136 2211 2286 2361 2436 2511 2586 2661 2736 2811 2886 2961]


In [43]:
passengers = np.array([
   [1, 0, 3, 22],
   [2, 1, 1, 38],
   [3, 1, 3, 26],
   [4, 1, 1, 35],
   [5, 0, 3, 35],
   [6, 0, 3, 18],
   [7, 0, 1, 54],
   [8, 0, 3, 2],
   [9, 1, 3, 27],
  [10, 1, 2, 14],
  [11, 1, 3, 4],
  [12, 1, 1, 58],
  [13, 0, 3, 20],
  [14, 0, 3, 39],
  [15, 0, 3, 14],
  [16, 1, 2, 55],
  [17, 0, 3, 2],
  [18, 1, 2, 12],
  [19, 0, 3, 31],
  [20, 1, 3, 8],
  [21, 0, 2, 35],
  [22, 1, 2, 34],
  [23, 1, 3, 15],
  [24, 1, 1, 28],
  [25, 0, 3, 8],
  [26, 1, 3, 38],
  [27, 0, 3, 2],
  [28, 0, 1, 1],
  [29, 1, 3, 5],
  [30, 0, 3, 18],
  [31, 0, 1, 40],
  [32, 1, 1, 70],
  [33, 1, 3, 33],
  [34, 0, 2, 66],
  [35, 0, 1, 28],
  [36, 0, 1, 42],
  [37, 1, 3, 5],
  [38, 0, 3, 18],
  [39, 0, 3, 18],
  [40, 1, 3, 14],
  [41, 0, 3, 40],
  [42, 0, 2, 27],
  [43, 0, 3, 29],
  [44, 1, 2, 0],
  [45, 1, 3, 19],
  [46, 0, 3, 33],
  [47, 0, 3, 14],
  [48, 1, 3, 22],
  [49, 0, 3, 41],
  [50, 0, 3, 18]
])
print(passengers.shape)

print(np.average(passengers, axis=0)[3])
avg_passengers = np.average(passengers[:,3])
print(avg_passengers)
old_passengers = np.max(passengers[:,3])
print(old_passengers)
young_passengers = np.min(passengers[:,3])
print(young_passengers)

total_pax = np.max(passengers,axis=0)[0]

no_survive = np.sum(passengers == 0 ,axis = 0 )[1]
survive = np.sum(passengers == 1 ,axis = 0 )[1]

print((survive/total_pax)*100)
print((no_survive/total_pax)*100)


(50, 4)
25.5
25.5
70
0
44.0
56.00000000000001


In [42]:
 

arr_2d = np.array([
    [1, 2, 3, 2],
    [5, 2, 7, 8],
    [2, 10, 2, 12]
])

specific_value = 2

# Count occurrences of 2 in each column
count_per_column = np.sum(arr_2d == specific_value, axis=0)
print(f"Occurrences of {specific_value} per column: {count_per_column}") # Output: [1 3 2 1]

# Count occurrences of 2 in each row
count_per_row = np.sum(arr_2d == specific_value, axis=1)
print(f"Occurrences of {specific_value} per row: {count_per_row}") 

Occurrences of 2 per column: [1 2 1 1]
Occurrences of 2 per row: [2 1 2]
